# -*- coding: utf-8 -*-
"""decisionTree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wfv9G8jnLf3OT5p86-pKH-CZpyROa7nY
"""

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv('/content/drive/MyDrive/breast_cancer_preprocessed.csv')

target_col = 'diagnosis'

all_features = [col for col in df.columns if col != target_col]

corr = df.corr(numeric_only=True)[target_col].abs().sort_values(ascending=False)
top_corr_features = corr.index[1:11].tolist()
print("Top 10 correlation features:", top_corr_features)

X_full = df[all_features]
y_full = df[target_col]

rf_for_fs = RandomForestClassifier(n_estimators=100, random_state=42)
rf_for_fs.fit(X_full, y_full)

feat_imp_df = pd.DataFrame({
    'feature': all_features,
    'importance': rf_for_fs.feature_importances_
}).sort_values(by='importance', ascending=False)

top_model_features = feat_imp_df['feature'][:10].tolist()
print("Top 10 RandomForest-importance features:", top_model_features)


X = df[all_features]
y = df[target_col]

X_train_all, X_test_all, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


X_train_corr = X_train_all[top_corr_features]
X_test_corr  = X_test_all[top_corr_features]

X_train_rf = X_train_all[top_model_features]
X_test_rf  = X_test_all[top_model_features]


dt_all = DecisionTreeClassifier(random_state=42)
dt_all.fit(X_train_all, y_train)
y_pred_all = dt_all.predict(X_test_all)

acc_all = accuracy_score(y_test, y_pred_all)
print("\n=== Decision Tree (ALL FEATURES) ===")
print("Accuracy:", round(acc_all * 100, 2), "%")
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_all))
print("\nClassification Report:\n", classification_report(y_test, y_pred_all))

dt_corr = DecisionTreeClassifier(random_state=42)
dt_corr.fit(X_train_corr, y_train)
y_pred_corr = dt_corr.predict(X_test_corr)

acc_corr = accuracy_score(y_test, y_pred_corr)
print("\n=== Decision Tree (TOP 10 CORRELATION FEATURES) ===")
print("Accuracy:", round(acc_corr * 100, 2), "%")
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_corr))
print("\nClassification Report:\n", classification_report(y_test, y_pred_corr))


dt_rf = DecisionTreeClassifier(random_state=42)
dt_rf.fit(X_train_rf, y_train)
y_pred_rf = dt_rf.predict(X_test_rf)

acc_rf = accuracy_score(y_test, y_pred_rf)
print("\n=== Decision Tree (TOP 10 RANDOMFOREST FEATURES) ===")
print("Accuracy:", round(acc_rf * 100, 2), "%")
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("\nClassification Report:\n", classification_report(y_test, y_pred_rf))

print("\n=== ACCURACY SUMMARY (Decision Tree) ===")
print(f"All features:           {round(acc_all * 100, 2)} %")
print(f"Top 10 corr features:   {round(acc_corr * 100, 2)} %")
print(f"Top 10 RF features:     {round(acc_rf * 100, 2)} %")