# -*- coding: utf-8 -*-
"""NaiveBayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kugujVGxTyQt55A3AXc5xX3JTatz3_9n
"""

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report


df = pd.read_csv('/content/drive/MyDrive/breast_cancer_preprocessed.csv')
display(df)


target_col = 'diagnosis'


correlation = df.corr(numeric_only=True)[target_col].abs().sort_values(ascending=False)


top_corr_features = correlation.index[1:11].tolist()
print("Top correlated features:", top_corr_features)


X = df[top_corr_features]
y = df[target_col]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


scaler = RobustScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled = pd.DataFrame(X_train_scaled, columns=X.columns, index=X_train.index)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X.columns, index=X_test.index)


nb_model = GaussianNB()
nb_model.fit(X_train_scaled, y_train)

y_pred_nb = nb_model.predict(X_test_scaled)


nb_acc = accuracy_score(y_test, y_pred_nb)
print("Naive Bayes Accuracy:", round(nb_acc * 100, 2), "%")
print("\nNaive Bayes Classification Report:")
print(classification_report(y_test, y_pred_nb))