# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11FclWC6haEbieTK8DJ2LrCoixa1qtSF-
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import RobustScaler


df = pd.read_csv('/content/breast-cancer (1).csv')
display(df)

display(df.isnull().sum())

df.info()
df.describe()

df.duplicated().sum()

df.drop('id', axis=1, inplace=True)

df['diagnosis'] = df ['diagnosis'].map({'M': 1, 'B': 0})
df.head()

features= df.drop(columns=['diagnosis'])

sns.set(style='whitegrid')

for col in features.columns:
    Q1 = features[col].quantile(0.25)
    Q3 = features[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = features[(features[col] < lower_bound) | (features[col] > upper_bound)][col]
    outlier_percentage = (len(outliers) / len(features[col])) * 100

    plt.figure(figsize=(6, 4))
    sns.boxplot(y=features[col], color='lightcoral', width=0.3)
    plt.title(f'Boxplot of {col}\nOutliers: {outlier_percentage:}%', fontsize=13)
    plt.ylabel(col)
    plt.xlabel('Value Distribution')
    plt.grid(True, linestyle='--', alpha=0.5)
    plt.show()

for col in features.columns:
    plt.figure(figsize=(6, 4))
    plt.scatter(x=range(len(features[col])), y=features[col], color='blue', alpha=0.7, s=25)
    plt.title(f'Scatter Plot of {col}', fontsize=13)
    plt.xlabel('Record Index')
    plt.ylabel(col)
    plt.grid(True, linestyle='--', alpha=0.5)
    plt.show()

corr = df.corr()
plt.figure(figsize=(24, 18))
sns.heatmap(
    corr,
    annot=True,
    fmt=".2f",
    cmap='coolwarm',
    linewidths=0.5,
    center=0,
    cbar_kws={'shrink': 0.8, 'label': 'Correlation Coefficient'}
)
plt.show()

sns.countplot(x='diagnosis', data=df, palette='Set2')
plt.title('Class Distribution of Diagnosis (Benign vs Malignant)', fontsize=14)
plt.xlabel('Diagnosis (0 = Benign, 1 = Malignant)')
plt.ylabel('Count')
plt.show()

for col in features.columns:
    mean_value = features[col].mean()
    print(f"The mean of '{col}' is: {mean_value:}")