# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19kK3vOc9ekqUgDwxNbOo4irtXFzPve95
"""

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv('/content/drive/MyDrive/breast_cancer_preprocessed.csv')

target_col = 'diagnosis'

all_features = [col for col in df.columns if col != target_col]

corr = df.corr(numeric_only=True)[target_col].abs().sort_values(ascending=False)
top_corr_features = corr.index[1:11].tolist()
print("Top 10 correlation features:", top_corr_features)

X_full = df[all_features]
y_full = df[target_col]

rf_for_fs = RandomForestClassifier(n_estimators=100, random_state=42)
rf_for_fs.fit(X_full, y_full)

feat_imp_df = pd.DataFrame({
    'feature': all_features,
    'importance': rf_for_fs.feature_importances_
}).sort_values(by='importance', ascending=False)

top_model_features = feat_imp_df['feature'][:10].tolist()
print("Top 10 RF-importance features:", top_model_features)

X = df[all_features]
y = df[target_col]

X_train_all, X_test_all, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

X_train_corr = X_train_all[top_corr_features]
X_test_corr  = X_test_all[top_corr_features]

X_train_rf = X_train_all[top_model_features]
X_test_rf  = X_test_all[top_model_features]

def run_svm(X_train, X_test, y_train, y_test, label=""):
    # Scale
    scaler = RobustScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    svm_clf = SVC(
        kernel='rbf',
        C=1.0,
        gamma='scale',
        probability=False,
        random_state=42
    )
    svm_clf.fit(X_train_scaled, y_train)
    y_pred = svm_clf.predict(X_test_scaled)

    acc = accuracy_score(y_test, y_pred)
    print(f"\n=== SVM {label} (RBF) ===")
    print("Accuracy:", round(acc * 100, 2), "%")
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("\nClassification Report:\n", classification_report(y_test, y_pred))

    return acc
acc_all = run_svm(X_train_all, X_test_all, y_train, y_test, "(ALL FEATURES)")

acc_corr = run_svm(X_train_corr, X_test_corr, y_train, y_test, "(TOP 10 CORR FEATURES)")

acc_rf = run_svm(X_train_rf, X_test_rf, y_train, y_test, "(TOP 10 RF FEATURES)")

print("\n=== ACCURACY SUMMARY (SVM, RBF) ===")
print(f"All features:           {round(acc_all * 100, 2)} %")
print(f"Top 10 corr features:   {round(acc_corr * 100, 2)} %")
print(f"Top 10 RF features:     {round(acc_rf * 100, 2)} %")